-
  font_size: 8
  from_dir: chill-bitmap
  to_dir: common
-
  font_size: 8
  from_dir: misaki/3040-309F Hiragana
  to_dir: common
-
  font_size: 8
  from_dir: misaki/30A0-30FF Katakana
  to_dir: common
-
  font_size: 8
  from_dir: galmuri/AC00-D7AF Hangul Syllables
  to_dir: common
-
  font_size: 8
  from_dir: galmuri/3130-318F Hangul Compatibility Jamo
  to_dir: common
-
  font_size: 8
  from_dir: chill-bitmap/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: zh_cn
-
  font_size: 8
  from_dir: boutique-bitmap/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: zh_tr
-
  font_size: 8
  from_dir: misaki/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: ja
-
  font_size: 8
  from_dir: galmuri/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: ko
-
  font_size: 8
  from_dir: galmuri/E000-F8FF Private Use Area
  to_dir: common
-
  font_size: 10
  from_dir: galmuri/AC00-D7AF Hangul Syllables
  to_dir: common
-
  font_size: 10
  from_dir: galmuri/3130-318F Hangul Compatibility Jamo
  to_dir: common
-
  font_size: 10
  from_dir: boutique-bitmap/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: zh_tr
-
  font_size: 10
  from_dir: galmuri/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: ko
-
  font_size: 10
  from_dir: galmuri/E000-F8FF Private Use Area
  to_dir: common
-
  font_size: 12
  from_dir: galmuri/AC00-D7AF Hangul Syllables
  to_dir: common
-
  font_size: 12
  from_dir: galmuri/3130-318F Hangul Compatibility Jamo
  to_dir: common
-
  font_size: 12
  from_dir: cubic-11/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: zh_tr
-
  font_size: 12
  from_dir: galmuri/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: ko
-
  font_size: 12
  from_dir: galmuri/E000-F8FF Private Use Area
  to_dir: common
