-
  font_size: 8
  from_dir: misaki/3040-309F Hiragana
  to_dir: common
-
  font_size: 8
  from_dir: misaki/30A0-30FF Katakana
  to_dir: common
-
  font_size: 8
  from_dir: galmuri-proportional/AC00-D7AF Hangul Syllables
  to_dir: common
-
  font_size: 8
  from_dir: galmuri-proportional/3130-318F Hangul Compatibility Jamo
  to_dir: common
-
  font_size: 8
  from_dir: chill-bitmap/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: zh_hans
-
  font_size: 8
  from_dir: boutique-bitmap/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: zh_hant
-
  font_size: 8
  from_dir: misaki/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: ja
-
  font_size: 8
  from_dir: galmuri-proportional/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: ko
-
  font_size: 10
  from_dir: galmuri-proportional/AC00-D7AF Hangul Syllables
  to_dir: common
-
  font_size: 10
  from_dir: galmuri-proportional/3130-318F Hangul Compatibility Jamo
  to_dir: common
-
  font_size: 10
  from_dir: boutique-bitmap/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: zh_hant
-
  font_size: 10
  from_dir: galmuri-proportional/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: ko
-
  font_size: 12
  from_dir: galmuri-proportional/AC00-D7AF Hangul Syllables
  to_dir: common
-
  font_size: 12
  from_dir: galmuri-proportional/3130-318F Hangul Compatibility Jamo
  to_dir: common
-
  font_size: 12
  from_dir: cubic-11/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: zh_hant
-
  font_size: 12
  from_dir: galmuri-proportional/4E00-9FFF CJK Unified Ideographs
  to_dir: common
  flavor: ko
