misaki:
  -
    font_file_name: misaki_gothic.ttf
    dump_dir_name: misaki
    font_size: 8
    rasterize_offset_y: 1
miseki-bitmap:
  -
    font_file_name: MisekiBitmap.ttf
    dump_dir_name: miseki-bitmap
    font_size: 8
    rasterize_offset_y: 1
boutique-bitmap-7x7:
  -
    font_file_name: BoutiqueBitmap7x7_{version}.ttf
    dump_dir_name: boutique-bitmap
    font_size: 8
    rasterize_offset_y: 1
boutique-bitmap-9x9:
  -
    font_file_name: BoutiqueBitmap9x9_{version}.ttf
    dump_dir_name: boutique-bitmap
    font_size: 10
    rasterize_offset_y: 1
cubic-11:
  -
    font_file_name: Cubic_11_{version}_R.woff2
    dump_dir_name: cubic-11
    font_size: 12
    rasterize_offset_x: -1
    rasterize_offset_y: 1
galmuri:
  -
    font_file_name: Galmuri7.ttf
    dump_dir_name: galmuri
    font_size: 8
    rasterize_offset_y: 1
  -
    font_file_name: Galmuri9.ttf
    dump_dir_name: galmuri
    font_size: 10
    rasterize_offset_y: 1
  -
    font_file_name: Galmuri11.ttf
    dump_dir_name: galmuri
    font_size: 12
    rasterize_offset_y: 1
  -
    font_file_name: GalmuriMono7.ttf
    dump_dir_name: galmuri-monospaced
    font_size: 8
    rasterize_offset_y: 1
