-
  name: miseki-bitmap
  repository_name: ItMarki/MisekiBitmap
  tag_name:
  asset_configs:
    -
      file_name: licensepack.zip
      copy_list:
        licensepack/LICENSE.txt: LICENSE.txt
        licensepack/MisekiBitmap.ttf: MisekiBitmap.ttf
-
  name: boutique-bitmap-7x7
  repository_name: scott0107000/BoutiqueBitmap7x7
  tag_name:
  asset_configs:
    -
      file_name: BoutiqueBitmap7x7_{version}.zip
      copy_list:
        OFL.txt: LICENSE.txt
        BoutiqueBitmap7x7_{version}.ttf:
-
  name: boutique-bitmap-9x9
  repository_name: scott0107000/BoutiqueBitmap9x9
  tag_name:
  asset_configs:
    -
      file_name: BoutiqueBitmap9x9_{version}.zip
      copy_list:
        OFL.txt: LICENSE.txt
        BoutiqueBitmap9x9_{version}.ttf:
-
  name: cubic-11
  repository_name: ACh-K/Cubic-11
  tag_name:
  asset_configs:
    -
      file_name: Cubic_11.zip
      copy_list:
        OFL.txt: LICENSE.txt
        fonts/web/Cubic_11_{version}_R.woff2: Cubic_11_{version}_R.woff2
-
  name: galmuri
  repository_name: quiple/galmuri
  tag_name:
  asset_configs:
    -
      file_name: Galmuri-v{version}.zip
      copy_list:
        dist/LICENSE.txt: LICENSE.txt
        dist/Galmuri7.ttf: Galmuri7.ttf
        dist/Galmuri9.ttf: Galmuri9.ttf
        dist/Galmuri11.ttf: Galmuri11.ttf
        dist/GalmuriMono7.ttf: GalmuriMono7.ttf
